name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tanzania_tours
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tanzania_tours
        run: npx prisma migrate deploy
      - name: Seed DB
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tanzania_tours
        run: node prisma/seed.js
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tanzania_tours
        run: npm test
      - name: Build
        run: npm run build
